name: CI HLG Image Push

on:
  pull_request:
    types: [closed]
    branches:
      - 'release/*'

jobs:
  build-push-image:
    runs-on: ubuntu-latest

    env:
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_USERNAME: ${{ secrets.DB_USERNAME }}

    steps:
      - name: Checkout código
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get branch name
        shell: bash
        run: echo "BRANCH_NAME=$(echo ${GITHUB_BASE_REF#release/} | cut -d'/' -f2)" >> $GITHUB_ENV

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: diegoneves/conectar-doacoes:${{ env.BRANCH_NAME }}
          build-args: |
            DB_NAME=${{ env.DB_NAME }}
            DB_PASSWORD=${{ env.DB_PASSWORD }}
            DB_USERNAME=${{ env.DB_USERNAME }}
