name: CI Prod Image Push

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  build-push-image:
    runs-on: ubuntu-latest
    env:
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_USERNAME: ${{ secrets.DB_USERNAME }}

    steps:
      - name: Checkout código
        uses: actions/checkout@v2

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1 

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1 

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push to Docker Hub
        run: |
          if [[ "${{ github.event.pull_request.merged == 'true' }}" ]]; then
            docker build -t diegoneves/conectar-doacoes:latest . --build-arg DB_NAME=${{ env.DB_NAME }} --build-arg DB_PASSWORD=${{ env.DB_PASSWORD }} --build-arg DB_USERNAME=${{ env.DB_USERNAME }}
            docker push diegoneves/conectar-doacoes:latest
          fi